from enum import Enum

class RelationshipStatus(str, Enum):
    PROPOSED = "PROPOSED"
    VALIDATED = "VALIDATED"
    DISPUTED = "DISPUTED"
    INVALIDATED = "INVALIDATED"
    SUPERSEDED = "SUPERSEDED"

class RelationshipType(str, Enum):
    DIRECT_EQUIVALENCE = "DIRECT_EQUIVALENCE"
    SYNTHETIC_REPLICATION = "SYNTHETIC_REPLICATION"
    PARITY = "PARITY"
    PROBABILITY_CONSISTENCY = "PROBABILITY_CONSISTENCY"
    TERM_LOCATION_BASIS = "TERM_LOCATION_BASIS"
    CASH_CARRY_LIKE = "CASH_CARRY_LIKE"
    RETAIL_RESALE_SPREAD = "RETAIL_RESALE_SPREAD"

class OpportunityClassification(str, Enum):
    STRICT_ARBITRAGE = "STRICT_ARBITRAGE"
    NEAR_ARBITRAGE = "NEAR_ARBITRAGE"

class Actionability(str, Enum):
    ACTIONABLE_PAPER = "ACTIONABLE_PAPER"
    BLOCKED = "BLOCKED"
    DEGRADED_STALE = "DEGRADED_STALE"

class OutcomeStatus(str, Enum):
    PENDING = "PENDING"
    PROVISIONAL = "PROVISIONAL"
    FINAL = "FINAL"
    DISPUTED = "DISPUTED"
    UNRESOLVABLE = "UNRESOLVABLE"
    CORRECTED = "CORRECTED"
